### PR TITLE
[T-6494][17.0][ADD]crm_assign_project: allows to automatically assign a project to a CRM lead

### PR DESCRIPTION
**Pull request by RogerSans**
This module allows to automatically assign a project to a CRM lead when a lead/opportunity is created through an email.
T-6494

@HaraldPanten 
@luis-ron

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional review: LGTM 👍🏻

**Comment by RogerSans** [comment]
@ValentinVinagre Can you review this pls? THX

**Review by ValentinVinagre — CHANGES_REQUESTED** [review]
ADD test's please

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
